// columns that make sense as buckets
const discreteColumns = [
	'source',
	'tmc',
	'severity',
	'desc',
	'number',
	'street',
	'side',
	'city',
	'county',
	'state',
	'zipcode',
	'timezone',
	'airportCode',
	'windDirection',
	'weatherCondition',
	'amenity',
	'bump',
	'crossing',
	'giveWay',
	'junction',
	'noExit',
	'railway',
	'roundabout',
	'station',
	'stop',
	'trafficCalming',
	'trafficSignal',
	'turningLoop',
	'sunriseSunsetNight',
	'civilTwilightNight',
	'nauticalTwilightNight',
	'astronomicalTwilightNight',
];

// columns that make sense as a Y axis
const numericColumns = [
	'severity',
	'distance',
	'temperature',
	'windChill',
	'humidity',
	'pressure',
	'visibility',
	'windSpeed',
	'precipitation',
];

// all columns
const columns = [
	'source',
	'tmc',
	'severity',
	'startTime',
	'endTime',
	'startLat',
	'startLng',
	'endLat',
	'endLng',
	'distance',
	'desc',
	'number',
	'street',
	'side',
	'city',
	'county',
	'state',
	'zipcode',
	'timezone',
	'airportCode',
	'weatherTimestamp',
	'temperature',
	'windChill',
	'humidity',
	'pressure',
	'visibility',
	'windDirection',
	'windSpeed',
	'precipitation',
	'weatherCondition',
	'amenity',
	'bump',
	'crossing',
	'giveWay',
	'junction',
	'noExit',
	'railway',
	'roundabout',
	'station',
	'stop',
	'trafficCalming',
	'trafficSignal',
	'turningLoop',
	'sunriseSunsetNight',
	'civilTwilightNight',
	'nauticalTwilightNight',
	'astronomicalTwilightNight',
];

module.exports = {
	discreteColumns,
	numericColumns,
	columns,
};